// src/constants/batchJobConstants.js

// 배치 작업 목록 조회
export const BATCH_JOB_LIST_REQUEST = 'BATCH_JOB_LIST_REQUEST';
export const BATCH_JOB_LIST_SUCCESS = 'BATCH_JOB_LIST_SUCCESS';
export const BATCH_JOB_LIST_FAIL = 'BATCH_JOB_LIST_FAIL';
export const BATCH_JOB_LIST_RESET = 'BATCH_JOB_LIST_RESET';

// 배치 작업 상세 조회
export const BATCH_JOB_DETAILS_REQUEST = 'BATCH_JOB_DETAILS_REQUEST';
export const BATCH_JOB_DETAILS_SUCCESS = 'BATCH_JOB_DETAILS_SUCCESS';
export const BATCH_JOB_DETAILS_FAIL = 'BATCH_JOB_DETAILS_FAIL';
export const BATCH_JOB_DETAILS_RESET = 'BATCH_JOB_DETAILS_RESET';

// 배치 작업 생성
export const BATCH_JOB_CREATE_REQUEST = 'BATCH_JOB_CREATE_REQUEST';
export const BATCH_JOB_CREATE_SUCCESS = 'BATCH_JOB_CREATE_SUCCESS';
export const BATCH_JOB_CREATE_FAIL = 'BATCH_JOB_CREATE_FAIL';
export const BATCH_JOB_CREATE_RESET = 'BATCH_JOB_CREATE_RESET';

// 배치 작업 상태 업데이트
export const BATCH_JOB_STATUS_UPDATE_REQUEST = 'BATCH_JOB_STATUS_UPDATE_REQUEST';
export const BATCH_JOB_STATUS_UPDATE_SUCCESS = 'BATCH_JOB_STATUS_UPDATE_SUCCESS';
export const BATCH_JOB_STATUS_UPDATE_FAIL = 'BATCH_JOB_STATUS_UPDATE_FAIL';
export const BATCH_JOB_STATUS_UPDATE_RESET = 'BATCH_JOB_STATUS_UPDATE_RESET';

// 배치 작업 삭제
export const BATCH_JOB_DELETE_REQUEST = 'BATCH_JOB_DELETE_REQUEST';
export const BATCH_JOB_DELETE_SUCCESS = 'BATCH_JOB_DELETE_SUCCESS';
export const BATCH_JOB_DELETE_FAIL = 'BATCH_JOB_DELETE_FAIL';
export const BATCH_JOB_DELETE_RESET = 'BATCH_JOB_DELETE_RESET';

// 배치 작업 항목 조회
export const BATCH_JOB_ITEMS_REQUEST = 'BATCH_JOB_ITEMS_REQUEST';
export const BATCH_JOB_ITEMS_SUCCESS = 'BATCH_JOB_ITEMS_SUCCESS';
export const BATCH_JOB_ITEMS_FAIL = 'BATCH_JOB_ITEMS_FAIL';
export const BATCH_JOB_ITEMS_RESET = 'BATCH_JOB_ITEMS_RESET';

// 배치 작업 로그 조회
export const BATCH_JOB_LOGS_REQUEST = 'BATCH_JOB_LOGS_REQUEST';
export const BATCH_JOB_LOGS_SUCCESS = 'BATCH_JOB_LOGS_SUCCESS';
export const BATCH_JOB_LOGS_FAIL = 'BATCH_JOB_LOGS_FAIL';
export const BATCH_JOB_LOGS_RESET = 'BATCH_JOB_LOGS_RESET';