// src/constants/marketplaceConstants.js

// 마켓플레이스 목록 조회
export const MARKETPLACE_LIST_REQUEST = 'MARKETPLACE_LIST_REQUEST';
export const MARKETPLACE_LIST_SUCCESS = 'MARKETPLACE_LIST_SUCCESS';
export const MARKETPLACE_LIST_FAIL = 'MARKETPLACE_LIST_FAIL';
export const MARKETPLACE_LIST_RESET = 'MARKETPLACE_LIST_RESET';

// 마켓플레이스 상세 조회
export const MARKETPLACE_DETAILS_REQUEST = 'MARKETPLACE_DETAILS_REQUEST';
export const MARKETPLACE_DETAILS_SUCCESS = 'MARKETPLACE_DETAILS_SUCCESS';
export const MARKETPLACE_DETAILS_FAIL = 'MARKETPLACE_DETAILS_FAIL';
export const MARKETPLACE_DETAILS_RESET = 'MARKETPLACE_DETAILS_RESET';

// 마켓플레이스 생성
export const MARKETPLACE_CREATE_REQUEST = 'MARKETPLACE_CREATE_REQUEST';
export const MARKETPLACE_CREATE_SUCCESS = 'MARKETPLACE_CREATE_SUCCESS';
export const MARKETPLACE_CREATE_FAIL = 'MARKETPLACE_CREATE_FAIL';
export const MARKETPLACE_CREATE_RESET = 'MARKETPLACE_CREATE_RESET';

// 마켓플레이스 수정
export const MARKETPLACE_UPDATE_REQUEST = 'MARKETPLACE_UPDATE_REQUEST';
export const MARKETPLACE_UPDATE_SUCCESS = 'MARKETPLACE_UPDATE_SUCCESS';
export const MARKETPLACE_UPDATE_FAIL = 'MARKETPLACE_UPDATE_FAIL';
export const MARKETPLACE_UPDATE_RESET = 'MARKETPLACE_UPDATE_RESET';

// 마켓플레이스 삭제
export const MARKETPLACE_DELETE_REQUEST = 'MARKETPLACE_DELETE_REQUEST';
export const MARKETPLACE_DELETE_SUCCESS = 'MARKETPLACE_DELETE_SUCCESS';
export const MARKETPLACE_DELETE_FAIL = 'MARKETPLACE_DELETE_FAIL';
export const MARKETPLACE_DELETE_RESET = 'MARKETPLACE_DELETE_RESET';

// 마켓플레이스 계정 추가
export const MARKETPLACE_ACCOUNT_CREATE_REQUEST = 'MARKETPLACE_ACCOUNT_CREATE_REQUEST';
export const MARKETPLACE_ACCOUNT_CREATE_SUCCESS = 'MARKETPLACE_ACCOUNT_CREATE_SUCCESS';
export const MARKETPLACE_ACCOUNT_CREATE_FAIL = 'MARKETPLACE_ACCOUNT_CREATE_FAIL';
export const MARKETPLACE_ACCOUNT_CREATE_RESET = 'MARKETPLACE_ACCOUNT_CREATE_RESET';

// 마켓플레이스 계정 수정
export const MARKETPLACE_ACCOUNT_UPDATE_REQUEST = 'MARKETPLACE_ACCOUNT_UPDATE_REQUEST';
export const MARKETPLACE_ACCOUNT_UPDATE_SUCCESS = 'MARKETPLACE_ACCOUNT_UPDATE_SUCCESS';
export const MARKETPLACE_ACCOUNT_UPDATE_FAIL = 'MARKETPLACE_ACCOUNT_UPDATE_FAIL';
export const MARKETPLACE_ACCOUNT_UPDATE_RESET = 'MARKETPLACE_ACCOUNT_UPDATE_RESET';

// 마켓플레이스 계정 삭제
export const MARKETPLACE_ACCOUNT_DELETE_REQUEST = 'MARKETPLACE_ACCOUNT_DELETE_REQUEST';
export const MARKETPLACE_ACCOUNT_DELETE_SUCCESS = 'MARKETPLACE_ACCOUNT_DELETE_SUCCESS';
export const MARKETPLACE_ACCOUNT_DELETE_FAIL = 'MARKETPLACE_ACCOUNT_DELETE_FAIL';
export const MARKETPLACE_ACCOUNT_DELETE_RESET = 'MARKETPLACE_ACCOUNT_DELETE_RESET';

// 카테고리 매핑 관리
export const MARKETPLACE_CATEGORY_MAPPING_UPDATE_REQUEST = 'MARKETPLACE_CATEGORY_MAPPING_UPDATE_REQUEST';
export const MARKETPLACE_CATEGORY_MAPPING_UPDATE_SUCCESS = 'MARKETPLACE_CATEGORY_MAPPING_UPDATE_SUCCESS';
export const MARKETPLACE_CATEGORY_MAPPING_UPDATE_FAIL = 'MARKETPLACE_CATEGORY_MAPPING_UPDATE_FAIL';
export const MARKETPLACE_CATEGORY_MAPPING_UPDATE_RESET = 'MARKETPLACE_CATEGORY_MAPPING_UPDATE_RESET';

// 필드 매핑 관리
export const MARKETPLACE_FIELD_MAPPING_UPDATE_REQUEST = 'MARKETPLACE_FIELD_MAPPING_UPDATE_REQUEST';
export const MARKETPLACE_FIELD_MAPPING_UPDATE_SUCCESS = 'MARKETPLACE_FIELD_MAPPING_UPDATE_SUCCESS';
export const MARKETPLACE_FIELD_MAPPING_UPDATE_FAIL = 'MARKETPLACE_FIELD_MAPPING_UPDATE_FAIL';
export const MARKETPLACE_FIELD_MAPPING_UPDATE_RESET = 'MARKETPLACE_FIELD_MAPPING_UPDATE_RESET';

// 마켓플레이스 동기화 로그 조회
export const MARKETPLACE_SYNC_LOGS_REQUEST = 'MARKETPLACE_SYNC_LOGS_REQUEST';
export const MARKETPLACE_SYNC_LOGS_SUCCESS = 'MARKETPLACE_SYNC_LOGS_SUCCESS';
export const MARKETPLACE_SYNC_LOGS_FAIL = 'MARKETPLACE_SYNC_LOGS_FAIL';
export const MARKETPLACE_SYNC_LOGS_RESET = 'MARKETPLACE_SYNC_LOGS_RESET';