// src/constants/productConstants.js

// 상품 목록 조회
export const PRODUCT_LIST_REQUEST = 'PRODUCT_LIST_REQUEST';
export const PRODUCT_LIST_SUCCESS = 'PRODUCT_LIST_SUCCESS';
export const PRODUCT_LIST_FAIL = 'PRODUCT_LIST_FAIL';
export const PRODUCT_LIST_RESET = 'PRODUCT_LIST_RESET';

// 상품 상세 조회
export const PRODUCT_DETAILS_REQUEST = 'PRODUCT_DETAILS_REQUEST';
export const PRODUCT_DETAILS_SUCCESS = 'PRODUCT_DETAILS_SUCCESS';
export const PRODUCT_DETAILS_FAIL = 'PRODUCT_DETAILS_FAIL';
export const PRODUCT_DETAILS_RESET = 'PRODUCT_DETAILS_RESET';

// 상품 생성
export const PRODUCT_CREATE_REQUEST = 'PRODUCT_CREATE_REQUEST';
export const PRODUCT_CREATE_SUCCESS = 'PRODUCT_CREATE_SUCCESS';
export const PRODUCT_CREATE_FAIL = 'PRODUCT_CREATE_FAIL';
export const PRODUCT_CREATE_RESET = 'PRODUCT_CREATE_RESET';

// 상품 수정
export const PRODUCT_UPDATE_REQUEST = 'PRODUCT_UPDATE_REQUEST';
export const PRODUCT_UPDATE_SUCCESS = 'PRODUCT_UPDATE_SUCCESS';
export const PRODUCT_UPDATE_FAIL = 'PRODUCT_UPDATE_FAIL';
export const PRODUCT_UPDATE_RESET = 'PRODUCT_UPDATE_RESET';

// 상품 삭제
export const PRODUCT_DELETE_REQUEST = 'PRODUCT_DELETE_REQUEST';
export const PRODUCT_DELETE_SUCCESS = 'PRODUCT_DELETE_SUCCESS';
export const PRODUCT_DELETE_FAIL = 'PRODUCT_DELETE_FAIL';
export const PRODUCT_DELETE_RESET = 'PRODUCT_DELETE_RESET';

// 상품 이미지 업로드
export const PRODUCT_UPLOAD_IMAGE_REQUEST = 'PRODUCT_UPLOAD_IMAGE_REQUEST';
export const PRODUCT_UPLOAD_IMAGE_SUCCESS = 'PRODUCT_UPLOAD_IMAGE_SUCCESS';
export const PRODUCT_UPLOAD_IMAGE_FAIL = 'PRODUCT_UPLOAD_IMAGE_FAIL';
export const PRODUCT_UPLOAD_IMAGE_RESET = 'PRODUCT_UPLOAD_IMAGE_RESET';

// 대량 상품 업로드
export const PRODUCT_BULK_UPLOAD_REQUEST = 'PRODUCT_BULK_UPLOAD_REQUEST';
export const PRODUCT_BULK_UPLOAD_SUCCESS = 'PRODUCT_BULK_UPLOAD_SUCCESS';
export const PRODUCT_BULK_UPLOAD_FAIL = 'PRODUCT_BULK_UPLOAD_FAIL';
export const PRODUCT_BULK_UPLOAD_RESET = 'PRODUCT_BULK_UPLOAD_RESET';

// 상품 엑셀 내보내기
export const PRODUCT_EXPORT_REQUEST = 'PRODUCT_EXPORT_REQUEST';
export const PRODUCT_EXPORT_SUCCESS = 'PRODUCT_EXPORT_SUCCESS';
export const PRODUCT_EXPORT_FAIL = 'PRODUCT_EXPORT_FAIL';
export const PRODUCT_EXPORT_RESET = 'PRODUCT_EXPORT_RESET';

// 마켓플레이스 연동
export const PRODUCT_SYNC_MARKETPLACE_REQUEST = 'PRODUCT_SYNC_MARKETPLACE_REQUEST';
export const PRODUCT_SYNC_MARKETPLACE_SUCCESS = 'PRODUCT_SYNC_MARKETPLACE_SUCCESS';
export const PRODUCT_SYNC_MARKETPLACE_FAIL = 'PRODUCT_SYNC_MARKETPLACE_FAIL';
export const PRODUCT_SYNC_MARKETPLACE_RESET = 'PRODUCT_SYNC_MARKETPLACE_RESET';